#
# About: Test image for Yoho object detection.
# Created by Wengjiakang at 04.01.2022
#

FROM ubuntu:18.04

# 更新包列表并安装必要的依赖
RUN apt-get update && apt-get install -y \
        software-properties-common \
        net-tools iputils-ping iproute2 telnet sudo git wget zip \
        libsm6 libxext6 libfontconfig1 libxrender1 libgl1-mesa-glx \
        libsndfile1 ffmpeg \
        python3 python3.8-dev python3.8-distutils curl

# 手动安装pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3.8 get-pip.py \
    && rm get-pip.py

# Source for the users in China, please uncomment this line
# RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# 安装Python包
RUN python3.8 -m pip install --default-timeout=1000 \
    gitpython>=3.1.20 \
    matplotlib>=3.3 \
    numpy>=1.23.5 \
    opencv-python>=4.1.1 \
    pillow>=10.3.0 \
    psutil \
    PyYAML>=5.3.1 \
    requests>=2.32.0 \
    scipy>=1.4.1 \
    thop>=0.1.1 \
    torch>=1.8.0 \
    torchvision>=0.9.0 \
    tqdm>=4.64.0 \
    ultralytics>=8.2.34 \
    pandas>=1.1.4 \
    seaborn>=0.11.0 \
    setuptools>=65.5.1

WORKDIR /app/yoho-emu

USER root

CMD ["bash"]
