#
# About: Test image for Yoho object detection.
# Created by Wengjiakang at 04.01.2022
# Modified by Huanzhuo Wu at 22.07.2022
#

FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

ADD /.wheels/* /

RUN apt-get update && apt-get install -y \
        software-properties-common \
        net-tools iputils-ping iproute2 telnet sudo git wget zip \
        libsm6 libxext6 libfontconfig1 libxrender1 libgl1-mesa-glx
# Python3 requirements
# RUN add-apt-repository ppa:deadsnakes/ppa       
RUN apt-get install -y python3 python3-dev python3-pip 
RUN sudo apt-get install -y libsndfile1 ffmpeg
RUN sudo -H pip3 install -U pip
RUN sudo -H pip install -U pip

RUN ls

# Source for the users isudo apt-get install libopenblas-devsudo apt-get install libopenblas-devn China, please uncomment this line
# RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip3 install --default-timeout=1000 numpy==1.17.3

# RUN pip3 install --default-timeout=1000 scipy==0.19.0 
RUN pip3 install /scipy-1.8.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

RUN pip3 install --default-timeout=1000 scikit-learn==0.24.1
# RUN pip3 install /scikit_learn-1.2.dev0-cp38-cp38-macosx_12_0_arm64.whl

RUN pip3 install --default-timeout=1000 museval==0.2.0  
RUN pip3 install --default-timeout=1000 pandas cffi progressbar2 scapy librosa torch==1.8.1 torchvision==0.9.1 torchaudio==0.12.0 --no-cache-dir

WORKDIR /app/yoho-emu

USER root

CMD ["bash"]
